aliases: []
creation_timestamp: 1705146315837
current_stage: None
description: null
last_updated_timestamp: 1705146315837
name: catboost
run_id: 665fcf7b55334ad6bf0d9818cf3d4745
run_link: null
source: /home/ml-srv-admin/xflow_project/mlflow/2/665fcf7b55334ad6bf0d9818cf3d4745/artifacts/catboost
status: READY
status_message: null
storage_location: /home/ml-srv-admin/xflow_project/mlflow/2/665fcf7b55334ad6bf0d9818cf3d4745/artifacts/catboost
user_id: null
version: 3
